"""insert defect value

Revision ID: 19fa5e142e11
Revises: 13050f26b984
Create Date: 2024-07-22 14:29:44.062886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19fa5e142e11'
down_revision: Union[str, None] = '13050f26b984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "INSERT INTO defects_types(id,defect_name) VALUES(1,'Ошибка маркировки')")

    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DELETE FROM defects_types WHERE id IN (1);")
    # ### end Alembic commands ###
