"""initial

Revision ID: f371fedebb90
Revises: 
Create Date: 2024-05-12 15:36:16.421923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f371fedebb90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multiboards',
    sa.Column('multiboard_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('multiboard_id')
    )
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_num', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectors_id'), 'sectors', ['id'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('multiboard_id', sa.Integer(), nullable=True),
    sa.Column('datamatrix', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['multiboard_id'], ['multiboards.multiboard_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('multiboard_id', sa.Integer(), nullable=True),
    sa.Column('url_image', sa.String(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['multiboard_id'], ['multiboards.multiboard_id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sectors_dm_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sector', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('coordinates_1', sa.String(), nullable=True),
    sa.Column('coordinates_2', sa.String(), nullable=True),
    sa.Column('coordinates_3', sa.String(), nullable=True),
    sa.Column('coordinates_4', sa.String(), nullable=True),
    sa.Column('coordinates_5', sa.String(), nullable=True),
    sa.Column('coordinates_6', sa.String(), nullable=True),
    sa.Column('coordinates_7', sa.String(), nullable=True),
    sa.Column('coordinates_8', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_sector'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments_of_inspection_table',
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments_of_inspection_table')
    op.drop_table('sectors_dm_position')
    op.drop_table('inspections')
    op.drop_table('boards')
    op.drop_index(op.f('ix_sectors_id'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_table('multiboards')
    op.drop_table('comments')
    # ### end Alembic commands ###
